### ISSUE TITLE
關於注音來源

### ISSUE THREAD

**Issue by spuggy0919** [ButTaiwan/bpmfvs#12]
最近要用注音表在做Ruby Annotation, 很高興能看到這個Source 
原本自己想找但一直找不到就自己也Sortting了一部分
有發現輸入法是最不可靠的來源 其目的只是為的可以打出字 所以很多都錯誤要小心使用
關於TXTA  除了輕聲 發現幾個和101 不一致 是 TXTA 減去101 一字多音 單音字表 部首表 
一共比對出40個差異 扣除輕聲字音 以下是TXT A多出的部分

4,佻,ㄊㄧㄠˊ,,,,,,,,,,,,,, # 101 年單音不取
13,噌,ㄘㄥ,,,,,,,,,,,,,,  #101 年單音不取
14,噴,˙ㄈㄣ,,,,,,,,,,,,,, #101  ̇ㄈㄣ併讀為ㄆㄣ。
15,坏,ㄆㄟˊ,,,,,,,,,,,,,, #101 ㄆㄟˊ、ㄆ丨併讀為ㄆㄟ。
16,埤,ㄅㄟ,,,,,,,,,,,,,,  #101 ㄆ丨ˋ併讀為ㄅ丨ˋ。
28,徊,ㄏㄨㄞˊ,,,,,,,,,,,,,, #101 ㄏㄨㄞˊ併讀為ㄏㄨㄟˊ。惟疊韻 詞「徘徊」或古詩詞押韻時，「 徊」仍可讀作ㄏㄨㄞˊ。
29,施,ㄧˋ,,,,,,,,,,,,,,    # 88 為ㄧˋ 101 1.ㄕ 2.丨 ˊ
30,潦,ㄌㄠˇ,,,,,,,,,,,,,,  # 101 ㄌㄠˇ併讀為ㄌㄠˋ。
31,燜,ㄇㄣˋ,,,,,,,,,,,,,,  # 101 ㄇㄣˋ併讀為ㄇㄣ。
37,莘,ㄕㄣ,,,,,,,,,,,,,, #101 新版審定音 ㄒ丨ㄣ
38,褶,ㄓㄜˇ,,,,,,,,,,,,,, #101 1.ㄒ丨ˊ併讀為ㄒㄩㄝˊ。 2.ㄓㄜˇ併讀為ㄓㄜˊ。

14,噴 38,褶 查過教育部重編國語辭典修訂版 這兩個字不一樣
但 38 漢典有

目前收集到 教育部的字典 但太多gif 很難搞 

至於標音我初部的想法是 用比對詞的方式嘗試所以盡量減少多音字 101的審定會視為最高優先 再來字典 再來缺的字打算用 ICU Transform to Latin 再轉注音 來找
不太了解IVS, IVS是否基於一個固定的注音碼本 如果是可能是不是同字型異體的 標準ㄧ樣需要建立  

以上僅供參考  感謝你們的付出

**Comment by spuggy0919** [comment]
FYI 僅供參考 應該不是issue 8p

**Comment by ButTaiwan** [comment]
101只是初稿，目前教育部、課本都還是以88年版本為準。
本專案88年音、101年音都收。

一字多音審訂表未收錄的字，才會去參考輸入法讀音。

**Comment by spuggy0919** [comment]
A 太少了  因為以A最高優先所以再提出說明清楚些
88 年版後面附錄 有6826個單字音加多音字共11075 
(Pdf最前面內文還有勘誤表) 

只是我的4253條多音分配採用XLS和88年的說明不Match 

資料來源: 教育部 國語一字多音審定表88年版
https://language.moe.gov.tw/001/Upload/Files/wxiao89/a.pdf

Xls 4253只有多音審定表 
0614,寗,ㄋ丨ㄥˋ ＃誤植與2071,甯同字

單音表重複字
Fail: Dunplicate Hanz or Bopo ㄘㄨㄣˊ-墫
Fail: Dunplicate Hanz or Bopo ㄨㄚ-窪

多音單音表與單音字重複
Warning: Repeat Han 嘛:ㄇㄚˊ ‧ㄇㄚ      
Warning: Repeat Han 奔:ㄅㄣ       
Warning: Repeat Han 篦:ㄅ丨ˋ       
Warning: Repeat Han 菫:ㄐ丨ㄣˇ  

多音單音表與造字更改
0614,寗,ㄋ丨ㄥˋ,,,,,,,  #改正一字
4008,冫食,ㄙㄨㄣ,ㄘㄢ,,,,,暫編於Unicode使用者造字區:FA7A8,

4007,飡,ㄙㄨㄣ,ㄘㄢ,,,,,,,,,,,,,
[88國語一字多音審訂表.zip](https://github.com/ButTaiwan/bpmfvs/files/7739343/88.zip)

**Comment by ButTaiwan** [comment]
基於穩定性問題（原來的版本有個讀音在新版本消失或是順序跑掉），本專案一旦收的讀音，就不會再刪了。（也就是你所說的固定的碼本，意即 phonic_table_Z.txt 就是本專案在維護的讀音標準表，包括讀音順序都不能更動。）
未來任何更新版本只會加讀音、加字，不會刪除任何讀音與國字。這點要先註明。

ps. 既然教育部最近這兩年似乎還在一直辦公聽會準備下個更新版本，如果沒有緊急性，或許教育部下個版本我再來更新會比較好。
