### ISSUE TITLE
溺 字破音ㄋ一ㄠˋ

### ISSUE THREAD

**Issue by mocsharp** [ButTaiwan/bpmfvs#13]
溺也有ㄋ一ㄠˋ(尿)的讀音，但目前只有ㄋ一ˋ的選項。

https://pedia.cloud.edu.tw/Entry/Detail/?title=%E6%BA%BA&search=%E6%BA%BA

**Comment by ButTaiwan** [comment]
凡《一字多音審訂表》有收錄的文字，所收讀音原則上以該表為準。
（刻意不收《一字多音審訂表》已經廢棄的讀音。）

![image](https://user-images.githubusercontent.com/5418570/233820151-22a38828-2043-4959-bb35-8124f2bb7285.png)

細節請參考讀音收錄原則： https://github.com/ButTaiwan/bpmfvs/tree/master/phonetic
