### ISSUE TITLE
請問我要怎麼把編碼回推注音符號?或者我有某個字跟它的注音符號要怎麼查在字體中的編碼?

### ISSUE THREAD

**Issue by a355337** [ButTaiwan/bpmfvs#16]
您好目前使用模型可以得到注音 https://github.com/GitYCC/g2pW
目前遇到找不到方法將得到的注音找到對應的編碼?e.g.
銀行 'ㄧㄣ2', 'ㄏㄤ2' 
行動'ㄒㄧㄥ2', 'ㄉㄨㄥ4'
我要怎麼直接
"銀" "ㄧㄣ2" mapping到IVS的對應的字?
或許細節我們可以線上會議聊聊

**Comment by ButTaiwan** [comment]
請查這個表。

https://github.com/ButTaiwan/bpmfvs/blob/master/phonetic/phonic_table_Z.txt

**Comment by a355337** [comment]
我覺得我沒有講清楚XDDD, 調整一下問法:
我要怎麼讓前端網頁正確顯示(假設我知道銀行 要念  'ㄧㄣ2', 'ㄏㄤ2'
剛剛追程式 追不到XDDDD
