### ISSUE TITLE
建議把「漢語拼音」改為「國音二式」

### ISSUE THREAD

**Issue by IanHo79** [ButTaiwan/bpmfvs#3]
試用 BpmfZihiKaiStd-Regular 字形檔的環境為 LibreOffice Calc v6.3.4.2 for macOS 10.13 ，使用fontforge.app 開啟 BpmfZihiKaiStd-Regular 來瀏覽字圖，發現純注音符號的字圖名稱用的是「漢語拼音」，這裡會推薦改用「國語注音符號第二式」（簡稱：國音二式）。
範例：ㄘㄞˋ（z_cai4 at 1114243） glyph name: z_cai4 (漢語拼音) 推薦改為 tsai4 （國音二式）（參考蔡英文總統臉書帳號名稱）。
這裡可以下載到中華民國行政院國家發展委員會全字庫整理的一千四百多筆的注音和國音二式對照表
https://data.gov.tw/dataset/5961
教育部 國語注音符號第二式
https://language.moe.gov.tw/001/Upload/files/site_content/M0001/er/c1.htm?open
這裡可以下載到民間第三方整理的兩千三百多筆的注音和國音二式對照表
https://sites.google.com/site/ianho7979/roctwmoepolyphone_unofficial_third-party_reproduction
還有發現多筆 國字＋注音 的注音/破音資料缺漏，之後會再整理補上。

**Comment by ButTaiwan** [comment]
教育部辭典本身也改用漢語拼音了。
實務上台灣的姓名、地名翻譯以前是威妥碼拼音為主（夾雜部分郵政拼音），後來就全面過渡為漢語拼音（與部分縣市用通用拼音），實際上國音二式是最使用最不普及的...。
（總統的 tsai 應該也是來自威妥碼拼音而不是注音二式。）

![image](https://user-images.githubusercontent.com/5418570/82163933-8209d480-98e0-11ea-9f7b-5a5a826bc746.png)

**Comment by IanHo79** [comment]
"cai" 口語上怎麼唸都像 「凱」，而不會像「蔡」，漢語拼音在臺灣環境而言，指鹿為馬的意味真的很濃。
參考文章：
一個中年男子小鄭 Eric 2266 的生活大小事 中文拼音 & 輸入法
https://ericecheng2266.wordpress.com/2016/05/10/中文拼音-輸入法/

**Comment by ButTaiwan** [comment]
https://language.moe.gov.tw/result.aspx?classify_sn=42&subclassify_sn=445&content_sn=3

本部依行政院97年9月16日營造國際生活環境推動小組第1次會議之決議，修正「中文譯音使用原則修正」（採用漢語拼音）函報行政院，行政院於97年12月18日以院臺教字第0970056233號函修正備查，並請有關機關據以實施。

**Comment by ButTaiwan** [comment]
另外， c 在德語、義大利語的讀音確實是 /ts/ 。

--
技術上是用什麼拼音實質沒有影響啦，目前也不是用真正的漢語拼音（為避免衝突，有些 v, eh 的轉置）。使用注音二式一樣也會碰到同樣需要轉置的問題（eh）。

就技術層面來說，例如Unicode標準裡注音符號的命名等實際上都是以漢語拼音為主（如 BOPOMOFO LETTER ZH），從原始注音檔案的字符命名起就已經是漢語拼音了（造字時沿用Unicode命名的關係）。在技術上每個步驟之間命名原則保持一致比較不會有 bug。現在若要更改，這會是牽一髮動全身的問題。

然而實務上這是只用於內部處理的資料，並非外顯資訊。現在要修改這個成本實在太高，但沒有實質效益。

--
另外，我自己對於威妥碼拼音跟漢語拼音都算熟，可以直接拼寫不需查表。反而對通用拼音跟國音二式最不熟（實際上最不通行），看懂大致可以，但不查表寫不出來。工作效率上也是不方便。

實務上是，現在多數華語教師現在熟悉的都是漢語拼音。即使是台灣編製的華語教材，都是用漢語拼音標註的。

**Comment by IanHo79** [comment]
所以是公家機關的問題。我只好試試看立法委員這個民意反應管道了，雖然我一個老百姓的聲音或許很渺小，至少我曾經嘗試過。

**Comment by IanHo79** [comment]
補充一下，有一種二次再利用BpmfZihiKaiStd-Regular.ttf字圖的操作情境，會讓所謂的內部處理的資料變成外顯資訊，就是用Fontforge.app選取一個要用到的純注音組合字圖的格子，匯出成SVG圖檔，這時候字圖名稱欄位內的字串，就會成為匯出的SVG檔名的其中一部分了。

**Comment by ButTaiwan** [comment]
基本上當你動用到 FontForge 或其他字型軟體時，這已經算是在檢視原始碼，就跟看 GitHub 上的原始碼沒什麼差別XD

**Comment by IanHo79** [comment]
GitHub上的原始碼我看不懂，只是之前有過使用fontforge.app把字圖匯出圖檔再拿來二次再利用的經驗，我是當成在操作繪製字形專用的向量圖繪製軟體而已。我也不會從零到有繪製向量圖（向量繪製操作過程我看不懂，我只會操作微軟小畫家）。

**Comment by ButTaiwan** [comment]
By the way，就是並非是字型軟體原始的用途了。
