### ISSUE TITLE
「儋」找不到「ㄉㄢˋ」音

### ISSUE THREAD

**Issue by IanHo79** [ButTaiwan/bpmfvs#6]
"Bpmf Zihi KaiStd"「儋」包含有預設顯示的「ㄉㄢˋ」音，不過我在 中華民國教育部 國語辭典簡編本、重編國語辭典修訂本、異體字字典、行政院國發會全字庫，都找不到「ㄉㄢˋ」音。能否將「儋」的預設顯示改為「ㄉㄢ」音？

**Comment by ButTaiwan** [comment]
修改讀音順序，就會與既有版本不相容。（也就是說之前已做的既有文件，這個字的讀音都會跑掉）

以向前相容為原則的角度來說，所有讀音都只能往後追加。既有的讀音順序都是不能改的。

**Comment by IanHo79** [comment]
那奢望「儋」能夠新增「ㄉㄢ」音。

**Comment by ButTaiwan** [comment]
應該有啊？

`儋	510B	B	ㄉㄢˋ	ㄉㄢ`

**Comment by IanHo79** [comment]
不好意思我找到 儋  ㄉㄢ 了。我前面看錯了。
